import{a as b,S as w,i as a}from"./assets/vendor-c493984e.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))d(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const m of r.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&d(m)}).observe(document,{childList:!0,subtree:!0});function s(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function d(t){if(t.ep)return;t.ep=!0;const r=s(t);fetch(t.href,r)}})();const f=async(e,o=1,s=15)=>{const d="https://pixabay.com/api/",t=new URLSearchParams({key:"44002996-fc99192b9f50d4483edb9d78f",q:e,image_type:"photo",orientation:"horizontal",safesearch:"true",page:o,per_page:s});return(await b.get(`${d}?${t.toString()}`)).data};function L(e){return`<li>
    <a href="${e.largeImageURL}">
      <img
        src="${e.webformatURL}" 
        alt="${e.tags}"
      />
    </a>
    <div class='info'>
      <p><span>Likes</span> ${e.likes}</p>
      <p><span>Views</span> ${e.views}</p>
      <p><span>Comments</span> ${e.comments}</p>
      <p><span>Downloads</span> ${e.downloads}</p>
    </div>
  </li>`}function h(e){return e.map(L).join("")}const y=document.querySelector(".search-form"),l=document.querySelector(".loader"),p=document.querySelector(".gallery"),c=document.querySelector(".load-more-btn");let g=1,u="",n=0,i=0;const C=new w(".gallery a");y.addEventListener("submit",async e=>{if(e.preventDefault(),u=e.target.elements.query.value.trim(),u===""){a.show({title:"Error",titleColor:"#d5cae4",message:"Please enter a search query!",messageColor:"#d5cae4",backgroundColor:"#EF4040",progressBarColor:"#d5cae4",close:!0,class:"custom-iziToast"});return}g=1,n=0,i=0,p.innerHTML="",c.style.display="none",l.style.display="block";try{const o=await f(u,g,15);if(l.style.display="none",o.hits.length===0){a.show({title:"No Results",titleColor:"#d5cae4",message:"Sorry, there are no images matching your search query. Please try again!",messageColor:"#d5cae4",backgroundColor:"#EF4040",progressBarColor:"#d5cae4",close:!0,class:"custom-iziToast"});return}n=o.totalHits,i=o.hits.length,a.show({title:"Congrats",titleColor:"#d5cae4",message:`We found ${n} images`,messageColor:"#d5cae4",backgroundColor:"#e1854c",progressBarColor:"#d5cae4",position:"topRight",close:!0,class:"custom-iziToast"});const s=h(o.hits);p.innerHTML=s,C.refresh(),i<n&&(c.style.display="block")}catch{l.style.display="none",a.show({title:"Error",titleColor:"#d5cae4",message:"Sorry, something went wrong. Please try again later!",messageColor:"#d5cae4",backgroundColor:"#EF4040",progressBarColor:"#d5cae4",close:!0,class:"custom-iziToast"})}y.reset()});c.addEventListener("click",async()=>{g+=1,c.style.display="none",l.style.display="block";try{const e=await f(u,g,15);l.style.display="none",i+=15;const o=h(e.hits);p.insertAdjacentHTML("beforeend",o);const{height:s}=p.firstElementChild.getBoundingClientRect();window.scrollBy({top:s*2,behavior:"smooth"}),C.refresh(),i<n?c.style.display="block":a.show({title:"End of Results",titleColor:"#d5cae4",message:"We're sorry, but you've reached the end of search results.",messageColor:"#d5cae4",backgroundColor:"#EF4040",progressBarColor:"#d5cae4",close:!0,class:"custom-iziToast"})}catch{l.style.display="none",a.show({title:"Error",titleColor:"#d5cae4",message:"Sorry, something went wrong. Please try again later!",messageColor:"#d5cae4",backgroundColor:"#EF4040",progressBarColor:"#d5cae4",close:!0,class:"custom-iziToast"})}});
//# sourceMappingURL=commonHelpers.js.map
